# window settings
remember_window_size no
initial_window_width 100c
initial_window_height 30c
window_padding_width 11

# Theme
background_opacity 1.0

# Cursor
cursor_shape block
cursor_blink_interval 0
cursor_trail 1
cursor_trail_decay 0.1 0.5
cursor_trail_start_threshold 3

# Scrollback
scrollback_lines 100000
wheel_scroll_multiplier 5.0


# Tab bar
tab_bar_style separator
tab_separator " "
tab_title_template "{index}"
active_tab_foreground   #7aa2f7
active_tab_background   #1a1b26
inactive_tab_foreground #565f89
inactive_tab_background #0f111a

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
map ctrl+0 goto_tab 10

#Terminal Bell ting ting 
enable_audio_bell no
# Shell
shell_integration no-cursor

# Font settings
font_family FiraCode Nerd Font
bold_font FiraCode Nerd Font Bold
italic_font FiraCode Nerd Font Italic
bold_italic_font FiraCode Nerd Font Bold Italic
font_size 18

############ TOKYO NIGHT THEME ############

# Background / foreground
background            #1a1b26
foreground            #c0caf5

# Cursor
cursor                #c0caf5
cursor_text_color     #1a1b26

# Selection (THIS fixes the ugly yellow)
selection_background  #33467c
selection_foreground  #c0caf5

# URL underline
url_color             #73daca

# Tab bar (matches Tokyo Night)
active_tab_foreground   #c0caf5
active_tab_background   #24283b
inactive_tab_foreground #565f89
inactive_tab_background #1a1b26

# Borders
active_border_color   #7aa2f7
inactive_border_color #414868

# Normal colors
color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6

# Bright colors
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

############ END TOKYO NIGHT ############

